services:
  mariadb:
    image: mariadb:12.2.2
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Qpq5nDb5MKD6v9bt8dPD
      MYSQL_PASSWORD: 886eOqVMmlHsayu6Vyxw
      MYSQL_USER: core
      MYSQL_DATABASE: core
    restart: on-failure

  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Qpq5nDb5MKD6v9bt8dPD
  #     MYSQL_PASSWORD: 886eOqVMmlHsayu6Vyxw
  #     MYSQL_USER: core
  #     MYSQL_DATABASE: core
  #   restart: on-failure

  core-one:
    image: hub.fity.tech/fidentity/procivis-one-core:0.0.0-dev
    ports:
      - 3210:3210
    environment:
      ONE_app__databaseUrl: "mysql://core:886eOqVMmlHsayu6Vyxw@mariadb/core"
      ONE_app__coreBaseUrl: "https://fidentity2.ngrok.dev"
      ONE_app__auth__mode: "UNSAFE_STATIC"
      ONE_app__auth__staticToken: "test"
      ONE_app__serverPort: "3210"
      ONE_app__enableOpenApi: "true"
      ONE_app__enableExternalEndpoints: "true"
      ONE_app__enableManagementEndpoints: "true"
      ONE_app__enableServerInfo: "true"
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  mariadb_data:
